#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void handle_int_signal(int sig) {  // sig stores the signal generated by handler
  printf("INT CAN'T KILL ME! %d\n", sig);
}

void handle_term_signal(
    int sig) {  // sig stores the signal generated by handler
  printf("TERM CAN'T KILL ME! %d\n", sig);
}

int main() {
  printf("MY PID IS: %d\n", getpid());

  struct sigaction sig;
  sig.sa_handler = handle_int_signal;
  sigaction(SIGINT, &sig, NULL);

  struct sigaction sig_2;
  sig_2.sa_handler = handle_term_signal;
  sigaction(SIGTERM, &sig_2, NULL);

  int i = 0;
  while (1) {
    printf("i = %d\n", i);
    i++;
    sleep(1);  // Wait for signal
  }
  return 0;
}
